apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor-zookeeper
    spec:
      containers:
        - name: server
          image: quay.io/rainchasers/zookeeper:v17
          env:
            - name: MYID
              value: "monitor"
